name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.12.1
        otp-version: 24.0

    - name: Install Olm C library
      run: sudo apt-get update && sudo apt-get install libolm-dev

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix compile && mix test

    - name: Check formatting
      run: mix format --check-formatted
